// ***********************************************************//// Default Course Script// This script is generated by creating a map in dim3 Map Editor.
// Edit it to your liking.
//// ***********************************************************

//
// construct map event
//
function mapConstruct(course){	var			i,cnt,name,type;			// setup camera			camera.setting.type=DIM3_CAMERA_TYPE_FPP;			// query spots to attach objects			cnt=map.spot.count;		for (i=0;i!=cnt;i++) {		name=map.spot.getName(i);		type=map.spot.getType(i);		if ((type=='Object') || (type=='Bot')) {			map.spot.attachObject(i,name,type,map.spot.getScript(i),map.spot.getParameter(i));		}	}}//// events//function event(course,mainEvent,subEvent,id,tick){	switch (mainEvent) {			case DIM3_EVENT_CONSTRUCT:			mapConstruct(course);			return;				}}