import os, string

env = Environment()
env.Append(CCFLAGS = ['-Wall', '-W', '-Wno-unused-parameter'])
env.Append(CPPPATH = ['/usr/include/js'])
env.Append(CPPDEFINES = {'D3_PCH': 1})
env.Append(LIBS = [
    'SDL', 'GLEW', 'GL', 'GLU', 'X11', 'openal', 'js', 'png'])

if ARGUMENTS.get('release', 0) == 0:
    env.Append(CCFLAGS = ['-g'])
else:
    env.Append(CPPDEFINES = {'NDEBUG': 1})

Export('env')

sources = []
for root, directories, files in os.walk('.'):
    for directory in directories:
        if string.count(directory, 'Headers'):
            env.Append(CPPPATH = [root + '/' + directory])
    
    for file in files:
        if os.path.splitext(file)[1] == '.c':
            sources += [root + '/' + file]

env.Program('Dim3 Engine', sources)
